# 1. Environment Setup

In [1]:
# Import the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf
from scipy.stats import zscore

In [2]:
import os

print(os.getcwd())
print(os.listdir("../../data/raw"))

N:\-LEARNING\--Portfolio\time-series-forecasting-project\notebooks\week1
['holidays.csv', 'oil.csv', 'stores.csv', 'timeseries.csv']

# 2. Data Loading

In [3]:
# Import holidays dataset
df_holidays = pd.read_csv("../../data/raw/holidays.csv")
display(df_holidays.head())

         date    locale locale_name                    description
0  2012-03-02     Local       Manta             Fundacion de Manta
1  2012-04-01  Regional    Cotopaxi  Provincializacion de Cotopaxi
2  2012-04-12     Local      Cuenca            Fundacion de Cuenca
3  2012-04-14     Local    Libertad      Cantonizacion de Libertad
4  2012-04-21     Local    Riobamba      Cantonizacion de Riobamba

In [4]:
# Import oil dataset
df_oil = pd.read_csv("../../data/raw/oil.csv")
display(df_oil.head())

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [5]:
# Import stories dataset
df_stores = pd.read_csv("../../data/raw/stores.csv")
display(df_stores.head())

   store_nbr           city                          region
0          1          Quito                       Pichincha
1          2          Quito                       Pichincha
2          3          Quito                       Pichincha
3          4          Quito                       Pichincha
4          5  Santo Domingo  Santo Domingo de los Tsachilas

In [6]:
# Import timeseries dataset
df_timeseries = pd.read_csv("../../data/raw/timeseries.csv")
display(df_timeseries.head())

         date  unit_sales
0  2013-01-02       582.0
1  2013-01-03       310.0
2  2013-01-04       338.0
3  2013-01-05       654.0
4  2013-01-06       979.0

# 3. Dataset Overview

In [7]:
# Check the size of each dataset
print("Holidays:", df_holidays.shape)
print("Stores:", df_stores.shape)
print("Oil:", df_oil.shape)
print("Time Series:", df_timeseries.shape)

Holidays: (350, 4)
Stores: (54, 3)
Oil: (1218, 2)
Time Series: (452, 2)

In [8]:
# Inspect column names in each dataset
print("Holidays columns:", df_holidays.columns.tolist())
print("Stores columns:", df_stores.columns.tolist())
print("Oil columns:", df_oil.columns.tolist())
print("Time Series columns:", df_timeseries.columns.tolist())

Holidays columns: ['date', 'locale', 'locale_name', 'description']
Stores columns: ['store_nbr', 'city', 'region']
Oil columns: ['date', 'dcoilwtico']
Time Series columns: ['date', 'unit_sales']